## Unit 4 Live Session Sandbox
## Jason Anastasopoulos (ljanastas@syr.edu)

### Topics:

- Functions exercise 4.2, 4.3, 4.4, Lab 2, Breakout Group Exercise.
- Try/except

## Exercise 4.2 on Functions (courtesy of Rebecca Boyer)

In [2]:
# Exercise 4.2 on Functions
#Exercise 1
#d.) ABD Zap ABC
#However, the python code written actually wouldn't work at all since the print() function needs those parantheses when defining what would be printed. The code SHOULD read:

def fred():
    print("Zap")
def jane():
    print("ABC")
jane()
fred()
jane()

ABC
Zap
ABC

In [4]:
#This program gets info from user and calculates pay
#gets the hours and rate
hours=input('Enter Hours: ')
rate=input('Enter Rate: ')
#compute the pay by converting the input strings and multiplying
pay=int(hours) * float(rate)
print('Pay: ',pay)

Enter Hours: 60
Enter Rate: 1.5
Pay:  90.0

# Exercise 4.3
## Courtesy of  Shan Jiang

In [4]:
# Solution 1
numlist = []

while (True):
    inp = input('Enter a number:')
    try:
        if inp == 'done': 
            
            break
        numlist.append(float(inp))
        
        
    except:
        print('Wrong format!')
        continue      
def stats():            
    print('Total is {:.2f}'.format(sum(numlist)))
    print('Count is {:d}'.format(int(len(numlist))))
    print('Average is {:.2f}'.format(sum(numlist)/int(len(numlist))))
stats()

Enter a number:60
Enter a number:60
Enter a number:60
Enter a number:done
Total is 180.00
Count is 3
Average is 60.00

# Exercise 4.3
## Courtesy of  STEPHEN OMONDI

In [6]:
# STEPHEN OMONDI. SAT/APR/25/2020
# Write a program which repeatedly reads numbers until the user enters 'done'. Once 'done' is entered, print out the total, count, and 
# average of the numbers. If the user enters anything other than a number, detect their mistake using try and except and print 
# an error message and skip to the next number
#

def numSummarizer(num = ""):
    allElements = []
    while num.lower() != 'done':
        num = input("Enter a number:")
        allElements.append(num)
    
    print("\nThe raw list is : ", allElements)
    
    
    # remove 'done' from the list
    try:
       allElements.remove('done')
    except:
        print('WARNING: \'done\' has already been removed from the list')
    
    print("\nRemoved \'done\' from the list. New list is: ", allElements)
    
    
    # convert all elements in the updated array into float values
    newElementsArray = []
    for item in range(0, len(allElements)):
        try:
            item = float(allElements[item])
            newElementsArray.append(item)
        except:
            print("\n\'{}\' is not a number and will be skipped.".format(allElements[item]))

    print("\nAll non numeric values have been removed: ", newElementsArray)
    
    
    # create summaries
    total = sum(newElementsArray)
    count = len(newElementsArray)
    average = total / count

    print("\nTotal: ", total)
    print("\nCount: ", count)
    print("\nAverage: ", round(average,2))

numSummarizer()

Enter a number:70
Enter a number:70
Enter a number:70
Enter a number:done

The raw list is :  ['70', '70', '70', 'done']

Removed 'done' from the list. New list is:  ['70', '70', '70']

All non numeric values have been removed:  [70.0, 70.0, 70.0]

Total:  210.0

Count:  3

Average:  70.0

# Exercise 4.4 Shan

In [33]:
import numpy as np


c = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
c

# Solution for (a)
#c[2:4,2:4] #[element chosen, columns w/in element]

# Solution for (b)
# b. Show how to create a one-dimensional array that sums the columns

#d = np.array([[sum(c[0:4,0])],[sum(c[0:4,1])],[sum(c[0:4,2])],[sum(c[0:4,3])],[sum(c[0:4,4])]])
#d

d = []

for i in range(len(c[0,])):
    d.append(sum(c[0:4,i]))

d

[34, 38, 42, 46, 50]

# Exercise 4.4 (a) Leland

In [25]:
c[-2:,2:4]
#nums = [1,2,3,4]
#nums[-3:]

array([[13, 14],
       [18, 19]])

In [6]:
#Exercise 2
def paycalculator():
     hours = float(input('Enter Hours: '))
     rate = float(input('Enter Rate: '))
     if hours > 40:
             pay = ((hours - 40) * (rate * 1.5)) + (40 * rate)
     else:
             pay = hours * rate
     print('Pay:', pay)

    
# ===

paycalculator()

# The above prompts users to enter their own data and has a conditional statement for when overtime is not a factor.

Enter Hours: 50
Enter Rate: 30
Pay: 1650.0

In [11]:
#Exercise 2
def paycalculator(hours,rate):
     if hours > 40:
             pay = ((hours - 40) * (rate * 1.5)) + (40 * rate)
     else:
             pay = hours * rate
            
     return(pay)

    
# ===
# Here we are calculating the total pay for a group of 5 employees given the overtime formula mentioned above.
totalpay  = []

employeehours = [45,60,80,30,15,40]
payrate = [200,50,20,10,500,350]

for i in range(0,len(employeehours)):
    emppaytemp = paycalculator(hours = employeehours[i],rate = payrate[i])
    totalpay.append(emppaytemp)
    
totalpay

[9500.0, 3500.0, 2000.0, 300, 7500, 14000]

## Exercise 4.3 Categorical Summarization (Courtesy of Anaya Fleary)

Write a program which repeatedly reads numbers until the user enters 'done'. Once 'done' is entered, print out the total, count, and average of the numbers. If the user enters anything other than a number, detect their mistake using try and except and print an error message and skip to the next number.

Submit your code and the results you got from running your program.

Check a couple of your classmates to see what they did.

In [12]:
sum = 0
count = 0
average = 0

while True:
  try:
    x = input("Enter a number: ")
    if (x == "done"): 
     break
    value = float(x)
    sum = value + sum
    count = count + 1
    average = sum / count
  except:
    print("Invalid input.")
print (sum, count, average)

Enter a number: 3
Enter a number: 2
Enter a number: 6
Enter a number: 10
Enter a number: done
21.0 4 5.25

## Exercises 4.4 Numeric Arrays (Courtesy of Meng Synn)

In [45]:
import numpy as np

# Generate a numpy array of size 4 by 5.
a = np.array([[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15], 
              [16, 17, 18, 19, 20]])

#a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])

# a. Use Index Slicing and show how to get the subarray consisting of the last two rows and the third and fourth columns.
#print(data[2:4])
#print(a[2:4,2:4])
# b. Show how to create a one-dimensional array that sums the columns
b = a.ravel()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Exercise 4.5

In [37]:
'''
  This program reads the data from the price of gasoline csv file 
    and uses only the numeric data
  Each line of the file has the year, followed by 12 months of gasoline prices
  We put the numeric fields in a numpy array and use the data for numeric operations.

  The outputs of the program are the averages of each month across the years
    and the averages for each year.
'''

import csv
import numpy as np

infile = '/Users/jason/Downloads/price_of_gasoline.xl (1).csv'

# create new empty lists:  years and prices come from data
yearsList = []
pricesList = []
# names of months for labeling results
monthList = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

# read the data
with open(infile, 'rU') as csvfile:
    # the csv file reader returns a list of the csv items on each line - note delimiter is comma
    priceReader = csv.reader(csvfile,  dialect='excel', delimiter=',')

    # from each line, a list of row items, make separate lists for years and for the prices
    for line in priceReader:
      # skip lines without data
      if line[0] == '' or line[0].startswith('Price') or line[0].startswith('Year'):
          continue
      else:
          try:
            # add the year to list
            yearsList.append(line[0])
            # append the prices (as strings) to the list
            pricesList.append(line[1:])
          except IndexError:
            print ('Error: ', line)
csvfile.close()

/Users/jason/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: DeprecationWarning: 'U' mode is deprecated

[['0.605',
  '0.600',
  '0.594',
  '0.592',
  '0.600',
  '0.616',
  '0.623',
  '0.628',
  '0.630',
  '0.629',
  '0.629',
  '0.626'],
 ['0.627',
  '0.637',
  '0.643',
  '0.651',
  '0.659',
  '0.665',
  '0.667',
  '0.667',
  '0.666',
  '0.665',
  '0.664',
  '0.665'],
 ['0.648',
  '0.647',
  '0.647',
  '0.649',
  '0.655',
  '0.663',
  '0.674',
  '0.682',
  '0.688',
  '0.690',
  '0.695',
  '0.705'],
 ['0.716',
  '0.730',
  '0.755',
  '0.802',
  '0.844',
  '0.901',
  '0.949',
  '0.988',
  '1.020',
  '1.028',
  '1.041',
  '1.065'],
 ['1.131',
  '1.207',
  '1.252',
  '1.264',
  '1.266',
  '1.269',
  '1.271',
  '1.267',
  '1.257',
  '1.250',
  '1.250',
  '1.258'],
 ['1.298',
  '1.382',
  '1.417',
  '1.412',
  '1.400',
  '1.391',
  '1.382',
  '1.376',
  '1.376',
  '1.371',
  '1.369',
  '1.365'],
 ['1.358',
  '1.334',
  '1.284',
  '1.225',
  '1.237',
  '1.309',
  '1.331',
  '1.323',
  '1.307',
  '1.295',
  '1.283',
  '1.260'],
 ['1.230',
  '1.187',
  '1.152',
  '1.215',
  '1.259',
  '1.277',
  '1.288',
  '1.285',
  '1.274',
  '1.255',
  '1.241',
  '1.231'],
 ['1.216',
  '1.209',
  '1.210',
  '1.227',
  '1.236',
  '1.229',
  '1.212',
  '1.196',
  '1.203',
  '1.209',
  '1.207',
  '1.193'],
 ['1.148',
  '1.131',
  '1.159',
  '1.205',
  '1.231',
  '1.241',
  '1.242',
  '1.229',
  '1.216',
  '1.204',
  '1.207',
  '1.208'],
 ['1.194',
  '1.120',
  '0.981',
  '0.888',
  '0.923',
  '0.955',
  '0.890',
  '0.843',
  '0.860',
  '0.831',
  '0.821',
  '0.823'],
 ['0.862',
  '0.905',
  '0.912',
  '0.934',
  '0.941',
  '0.958',
  '0.971',
  '0.995',
  '0.990',
  '0.976',
  '0.976',
  '0.961'],
 ['0.933',
  '0.913',
  '0.904',
  '0.930',
  '0.955',
  '0.955',
  '0.967',
  '0.987',
  '0.974',
  '0.957',
  '0.949',
  '0.930'],
 ['0.918',
  '0.926',
  '0.940',
  '1.065',
  '1.119',
  '1.114',
  '1.092',
  '1.057',
  '1.029',
  '1.027',
  '0.999',
  '0.980'],
 ['1.042',
  '1.037',
  '1.023',
  '1.044',
  '1.061',
  '1.088',
  '1.084',
  '1.190',
  '1.294',
  '1.378',
  '1.377',
  '1.354'],
 ['1.247',
  '1.143',
  '1.082',
  '1.104',
  '1.156',
  '1.160',
  '1.127',
  '1.140',
  '1.143',
  '1.122',
  '1.134',
  '1.123'],
 ['1.073',
  '1.054',
  '1.058',
  '1.079',
  '1.136',
  '1.179',
  '1.174',
  '1.158',
  '1.158',
  '1.154',
  '1.159',
  '1.136'],
 ['1.117',
  '1.108',
  '1.098',
  '1.112',
  '1.129',
  '1.130',
  '1.109',
  '1.097',
  '1.085',
  '1.127',
  '1.113',
  '1.070'],
 ['1.043',
  '1.051',
  '1.045',
  '1.064',
  '1.080',
  '1.106',
  '1.136',
  '1.182',
  '1.177',
  '1.152',
  '1.163',
  '1.143'],
 ['1.129',
  '1.120',
  '1.115',
  '1.140',
  '1.200',
  '1.226',
  '1.195',
  '1.164',
  '1.148',
  '1.127',
  '1.101',
  '1.101'],
 ['1.129',
  '1.124',
  '1.162',
  '1.251',
  '1.323',
  '1.299',
  '1.272',
  '1.240',
  '1.234',
  '1.227',
  '1.250',
  '1.260'],
 ['1.261',
  '1.255',
  '1.235',
  '1.231',
  '1.226',
  '1.229',
  '1.205',
  '1.253',
  '1.277',
  '1.242',
  '1.213',
  '1.177'],
 ['1.131',
  '1.082',
  '1.041',
  '1.052',
  '1.092',
  '1.094',
  '1.079',
  '1.052',
  '1.033',
  '1.042',
  '1.028',
  '0.986'],
 ['0.972',
  '0.955',
  '0.991',
  '1.177',
  '1.178',
  '1.148',
  '1.189',
  '1.255',
  '1.280',
  '1.274',
  '1.264',
  '1.298'],
 ['1.301',
  '1.369',
  '1.541',
  '1.506',
  '1.498',
  '1.617',
  '1.593',
  '1.51',
  '1.582',
  '1.559',
  '1.555',
  '1.489'],
 ['1.472',
  '1.484',
  '1.447',
  '1.564',
  '1.729',
  '1.64',
  '1.482',
  '1.427',
  '1.531',
  '1.362',
  '1.263',
  '1.131'],
 ['1.139',
  '1.13',
  '1.241',
  '1.407',
  '1.421',
  '1.404',
  '1.412',
  '1.423',
  '1.422',
  '1.449',
  '1.448',
  '1.394'],
 ['1.473',
  '1.641',
  '1.748',
  '1.659',
  '1.542',
  '1.514',
  '1.524',
  '1.628',
  '1.728',
  '1.603',
  '1.535',
  '1.494'],
 ['1.592',
  '1.672',
  '1.766',
  '1.833',
  '2.009',
  '2.041',
  '1.939',
  '1.898',
  '1.891',
  '',
  '',
  '']]

In [ ]:
print ("Read", len(yearsList), "years of prices")

# make a numpy array for the strings
data = np.array(pricesList)
print('Shape of Prices data', data.shape)

# convert the empty strings to strings of zeros, using a Boolean mask to find empty strings
data[data == ''] = '0'

# now we can convert the whole thing to float without getting conversion errors for the empty strings
prices = data.astype(np.float)

#print(prices)

# compute the average price for each month (or use mean)
# sum along the columns
monthTotalPrices = np.sum(prices, axis = 0)
# divide by number of years to get average
monthAveragePrices = monthTotalPrices / len(yearsList)

#print(monthAveragePrices)
print ("\nAverage gas price for each month\n")

# print the average price for each month
for i, mon in enumerate(monthList):
	print (mon, ':', monthAveragePrices[i])

# compute the average price for each year up to the last one with missing data
# sum along the rows
yearTotalPrices = np.sum(prices, axis = 1)
# divide by number of months to get average
yearAveragePrices = yearTotalPrices / 12

#print(monthAveragePrices)
print ("\nAverage gas price for each year\n")

# print the 
for i, year in enumerate(yearsList[ :-1]):
  print (year ,':', yearAveragePrices[i])

# or display the monthly averages as a simple plot

import matplotlib.pyplot as pp

x = np.arange(12)
pp.xticks(x,monthList)
pp.plot(x, monthAveragePrices)
pp.show()


# or we can also display the years with a simple plot
x = np.arange(len(yearsList)-1)
pp.xticks(x,yearsList)
pp.plot(x, yearAveragePrices[:-1])
pp.show()

# Done!

# Dealing with Errors

### Our code without defining an exception

In [9]:
    score = input("Enter score: ")
    score =float (score)
    if score >= 0.9 and score <=1.0:
        print ("Grade: A ")
    elif score >= 0.8 and score <=0.9 :
        print ("Grade: B ")
    elif score >= 0.7 and score <=0.8:
        print ("Grade: C ") 
    elif score >= 0.6 and score <=0.7 :
        print ("Grade: D ") 
    elif score < 0.6 :
        print ("Grade: F ")
    else:
        print ("Bad score")

Enter score: grade

ValueError: could not convert string to float: 'grade'

### Code after defining an exception

In [11]:
try:
    score = input("Enter score: ")
    score =float (score)
    if score >= 0.9 and score <=1.0:
        print ("Grade: A ")
    elif score >= 0.8 and score <=0.9 :
        print ("Grade: B ")
    elif score >= 0.7 and score <=0.8:
        print ("Grade: C ") 
    elif score >= 0.6 and score <=0.7 :
        print ("Grade: D ") 
    elif score < 0.6 :
        print ("Grade: F ")
    else:
        print ("Bad score")
except ValueError:
    print("Sorry, you entered a string when we expected a number between 0 and 1, try again")

Enter score: hfjkhsd-23879uyi hsdfsf
Sorry, you entered a string when we expected a number between 0 and 1, try again

## Dictionaries

In [41]:
emptydict = dict()
#type(emptydict)

phonedict = {'eric': '454-5555', 'john':'454-5195'}

len(phonedict)

# Retrieve the keys
phonekeys = phonedict.keys()

# Retreive the values
phonevalues = phonedict.values()

# Look up a value  in the dictionary 
phonedict['john']

'454-5195'

## Reading and manipulating csv files

In [42]:
# This program reads the data from the states tsv file

#     Each line has the state name, abbreviation, postal code, area and population.

# It stores the items in each line in a dictionary whose keys represent the column names.

#     It print the state name, abbreviation and population for each state.


import csv

infile = 'states_data.tsv'
#infile.path  = '/Users/jason/Dropbox/Teaching/Syracuse-Scripting-2019/Unit 3/states_data.tsv'


# create new empty list

statesList = []

with open(infile, 'r') as csvfile:

    # the csv file reader returns a list of the csv items on each line

    stateReader = csv.reader(csvfile,  dialect='excel', delimiter='\t')


    # from each line, a list of row items, put each element in a dictionary

    #   with a key representing the data

    for line in stateReader:

      # skip lines without data, specific for each file to catch non-data lines

      if line[0] == '' or line[0].startswith('Data') or line[0].startswith('*'):

          continue

      else:

          # create a dictionary for each state

          state = {}

          # add each piece of data under a key representing that column data

          state['name'] = line[0]

          state['abbrev'] = line[1]

          state['code'] = line[2]

          state['area'] = int(line[3].replace(',',''))

          state['pop'] = int(line[4].replace(',',''))

          # The dictionary for Alabama
          # state = {'name': 'Alabama', 'abbrev': 'Ala.', 'code':'AL', 'area': 52423, 'pop':4040587}
          # add this state to the list

          statesList.append(state)

statesList

#csvfile.close()


#print ("Read", len(statesList), "state data")


# print a few fields from all of the states read from the file


#for state in statesList:

#    print ('State:', state['name'], ' Abrv: ', state['abbrev'], ' Population: ', state['pop'])

[{'name': 'Alabama',
  'abbrev': 'Ala.',
  'code': 'AL',
  'area': 52423,
  'pop': 4040587},
 {'name': 'Alaska',
  'abbrev': 'Alaska',
  'code': 'AK',
  'area': 656424,
  'pop': 550043},
 {'name': 'Arizona',
  'abbrev': 'Ariz.',
  'code': 'AZ',
  'area': 114006,
  'pop': 3665228},
 {'name': 'Arkansas',
  'abbrev': 'Ark.',
  'code': 'AR',
  'area': 53182,
  'pop': 2350725},
 {'name': 'California',
  'abbrev': 'Calif.',
  'code': 'CA',
  'area': 163707,
  'pop': 29769021},
 {'name': 'Colorado',
  'abbrev': 'Colo.',
  'code': 'CO',
  'area': 104100,
  'pop': 3294394},
 {'name': 'Connecticut',
  'abbrev': 'Conn.',
  'code': 'CT',
  'area': 5544,
  'pop': 3287116},
 {'name': 'Delaware',
  'abbrev': 'Del.',
  'code': 'DE',
  'area': 2489,
  'pop': 666168},
 {'name': 'District of Columbia',
  'abbrev': 'D.C.',
  'code': 'DC',
  'area': 68,
  'pop': 606900},
 {'name': 'Florida',
  'abbrev': 'Fla.',
  'code': 'FL',
  'area': 65756,
  'pop': 12937926},
 {'name': 'Georgia',
  'abbrev': 'Ga.',
  'code': 'GA',
  'area': 59441,
  'pop': 6478216},
 {'name': 'Hawaii',
  'abbrev': 'Hawaii',
  'code': 'HI',
  'area': 10932,
  'pop': 1108229},
 {'name': 'Idaho',
  'abbrev': 'Idaho',
  'code': 'ID',
  'area': 83574,
  'pop': 1006749},
 {'name': 'Illinois',
  'abbrev': 'Ill.',
  'code': 'IL',
  'area': 57918,
  'pop': 11430602},
 {'name': 'Indiana',
  'abbrev': 'Ind.',
  'code': 'IN',
  'area': 36420,
  'pop': 5544159},
 {'name': 'Iowa',
  'abbrev': 'Iowa',
  'code': 'IA',
  'area': 56276,
  'pop': 2776755},
 {'name': 'Kansas',
  'abbrev': 'Kans.',
  'code': 'KS',
  'area': 82282,
  'pop': 2477574},
 {'name': 'Kentucky',
  'abbrev': 'Ky.',
  'code': 'KY',
  'area': 40411,
  'pop': 3685296},
 {'name': 'Louisiana',
  'abbrev': 'La.',
  'code': 'LA',
  'area': 51843,
  'pop': 4219973},
 {'name': 'Maine',
  'abbrev': 'Maine',
  'code': 'ME',
  'area': 35387,
  'pop': 1227928},
 {'name': 'Maryland',
  'abbrev': 'Md.',
  'code': 'MD',
  'area': 12407,
  'pop': 4781468},
 {'name': 'Massachusetts',
  'abbrev': 'Mass.',
  'code': 'MA',
  'area': 10555,
  'pop': 6016425},
 {'name': 'Michigan',
  'abbrev': 'Mich.',
  'code': 'MI',
  'area': 96705,
  'pop': 9295297},
 {'name': 'Minnesota',
  'abbrev': 'Minn.',
  'code': 'MN',
  'area': 86943,
  'pop': 4375099},
 {'name': 'Mississippi',
  'abbrev': 'Miss.',
  'code': 'MS',
  'area': 48434,
  'pop': 2573216},
 {'name': 'Missouri',
  'abbrev': 'Mo.',
  'code': 'MO',
  'area': 69709,
  'pop': 5117073},
 {'name': 'Montana',
  'abbrev': 'Mont.',
  'code': 'MT',
  'area': 147046,
  'pop': 799065},
 {'name': 'Nebraska',
  'abbrev': 'Nebr.',
  'code': 'NE',
  'area': 77358,
  'pop': 1578385},
 {'name': 'Nevada',
  'abbrev': 'Nev.',
  'code': 'NV',
  'area': 110567,
  'pop': 1201833},
 {'name': 'New Hampshire',
  'abbrev': 'N.H.',
  'code': 'NH',
  'area': 9351,
  'pop': 1109252},
 {'name': 'New Jersey',
  'abbrev': 'N.J.',
  'code': 'NJ',
  'area': 8722,
  'pop': 7730188},
 {'name': 'New Mexico',
  'abbrev': 'N.Mex.',
  'code': 'NM',
  'area': 121598,
  'pop': 1515069},
 {'name': 'New York',
  'abbrev': 'N.Y.',
  'code': 'NY',
  'area': 54471,
  'pop': 17990455},
 {'name': 'North Carolina',
  'abbrev': 'N.C.',
  'code': 'NC',
  'area': 53821,
  'pop': 6628637},
 {'name': 'North Dakota',
  'abbrev': 'N.Dak.',
  'code': 'ND',
  'area': 70704,
  'pop': 638800},
 {'name': 'Ohio',
  'abbrev': 'Ohio',
  'code': 'OH',
  'area': 44828,
  'pop': 10847115},
 {'name': 'Oklahoma',
  'abbrev': 'Okla.',
  'code': 'OK',
  'area': 69903,
  'pop': 3145585},
 {'name': 'Oregon',
  'abbrev': 'Oreg.',
  'code': 'OR',
  'area': 98386,
  'pop': 2842321},
 {'name': 'Pennsylvania',
  'abbrev': 'Pa.',
  'code': 'PA',
  'area': 46058,
  'pop': 11881643},
 {'name': 'Rhode Island',
  'abbrev': 'R.I.',
  'code': 'RI',
  'area': 1545,
  'pop': 1003464},
 {'name': 'South Carolina',
  'abbrev': 'S.C.',
  'code': 'SC',
  'area': 32008,
  'pop': 3468703},
 {'name': 'South Dakota',
  'abbrev': 'S.Dak.',
  'code': 'SD',
  'area': 77121,
  'pop': 696004},
 {'name': 'Tennessee',
  'abbrev': 'Tenn.',
  'code': 'TN',
  'area': 42146,
  'pop': 4877185},
 {'name': 'Texas',
  'abbrev': 'Tex.',
  'code': 'TX',
  'area': 268601,
  'pop': 16986510},
 {'name': 'Utah',
  'abbrev': 'Utah',
  'code': 'UT',
  'area': 84904,
  'pop': 1722850},
 {'name': 'Vermont',
  'abbrev': 'Vt.',
  'code': 'VT',
  'area': 9615,
  'pop': 562758},
 {'name': 'Virginia',
  'abbrev': 'Va.',
  'code': 'VA',
  'area': 42777,
  'pop': 6187358},
 {'name': 'Washington',
  'abbrev': 'Wash.',
  'code': 'WA',
  'area': 71302,
  'pop': 4866692},
 {'name': 'West Virginia',
  'abbrev': 'W.Va.',
  'code': 'WV',
  'area': 24231,
  'pop': 1793477},
 {'name': 'Wisconsin',
  'abbrev': 'Wis.',
  'code': 'WI',
  'area': 65499,
  'pop': 4891769},
 {'name': 'Wyoming',
  'abbrev': 'Wyo.',
  'code': 'WY',
  'area': 97818,
  'pop': 453588},
 {'name': 'United States',
  'abbrev': '',
  'code': '',
  'area': 3787316,
  'pop': 248691873}]

# Sorting lists

In [1]:
# List sorting code here

# Functions and documentation strings

In [12]:
# Function code here.
def hello():
    print('Hello')

In [13]:
hello()

Hello

In [16]:
def area(width, height):
    a = width*height
    return a

In [17]:
area(3,4)

12